apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DJANGO_DEBUG: "False"
  USE_DOCKER: "yes"
  DJANGO_ADMIN_URL: "admin/"
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_SECRET_KEY: "CHANGEME"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,.{{ copier__domain_name }}"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,https://{{ copier__domain_name }}"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_DB: "{{ copier__project_slug }}"
  POSTGRES_USER: "{{ copier__project_slug }}"
  REDIS_URL: "redis://redis:6379/1"
  # todo: see if PYDEVD_USE_* can be removed later, I was getting this error
  #  with pydevd-pycharm==243.26053.29:
  # cannot import name 'trace_dispatch' from '_pydevd_bundle.pydevd_trace_dispatch'
  # (/app/lib/python3.12/site-packages/_pydevd_bundle/pydevd_trace_dispatch.py)
  # Also probably need to add cython to local.in in that case.
  PYDEVD_USE_CYTHON: "NO"
  PYDEVD_USE_FRAME_EVAL: "NO"
  PYTHONBREAKPOINT: "" # "utils.pycharm_debugger" for pycharm, "utils.vscode_debugger" for VS Code
  DEBUGGER_PORT: "" # "6400" for pycharm, "5678" for VS Code
{%- if copier__mail_service == 'Mailgun' %}
  MAILGUN_DOMAIN: "{{ copier__domain_name }}"
  MAILGUN_API_URL: "https://api.mailgun.net/v3"{%- endif %}
{%- if copier__use_celery %}
  CELERY_BROKER_URL: "redis://redis:6379/0"
  FLOWER_BROKER_URL: "redis://redis:6379/0"
  FLOWER_ADDRESS: "0.0.0.0"
  FLOWER_PORT: "5555"{%- endif %}
  # S3 storage access
  DJANGO_AWS_REGION_NAME: "{{ copier__aws_region }}"
  DJANGO_AWS_STORAGE_BUCKET_NAME: "CHANGEME_S3_BUCKET_NAME"
{% if copier__use_sentry %}
  SENTRY_DSN_BACKEND: ""
  ENVIRONMENT: "dev"
  VITE_SENTRY_DSN_FRONTEND: ""
  VITE_ENVIRONMENT: "dev"{% endif %}
